### ISSUE TITLE
OpenGL error on the headless server

### ISSUE THREAD

**Issue by LYK-love** [chandar-lab/Recall2Imagine#5]
Hi, I tried to run the command
```
python recall2imagine/train.py \
    --configs mmaze --task gym_memory_maze:MemoryMaze-9x9-v0 \
    --wdb_name memory_maze_9x9 \
    --logdir ./logs_memory_maze_9x9
```
on my headless server. But I got this error:
```text
Traceback (most recent call last):
  File "recall2imagine/train.py", line 6, in <module>
    import mujoco
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/mujoco/__init__.py", line 47, in <module>
    from mujoco.gl_context import *
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/mujoco/gl_context.py", line 38, in <module>
    from mujoco.osmesa import GLContext as _GLContext
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/mujoco/osmesa/__init__.py", line 31, in <module>
    from OpenGL import GL
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

Is there any way to solve this?
Thanks!

I have installed all the dependencies specified in the `readme.md`. My system config is: Ubuntu22.04, x86_64 with CUDA Version: 12.4.

**Comment by artemZholus** [comment]
Hi , @LYK-love . This is a known OpenGL error that appears when running OpenGL rendering in mujoco. The easiest way to fix that is to use software rendering.

Just do 
```sh
export MUJOCO_GL=osmesa
```
Before running the training. In our paper, always used software rendering and the training throughput is reported using that. I am closing the issue. Please reopen it if you still face this problem.
